# Generated by Django 5.2.8 on 2025-11-25 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('anno', models.PositiveIntegerField()),
                ('genere', models.CharField(blank=True, max_length=100)),
                ('regista', models.CharField(blank=True, max_length=100)),
                ('visto', models.BooleanField(default=False)),
                ('dimensione_file_mb', models.FloatField(blank=True, help_text='Dimensione in MB', null=True)),
                ('codifica', models.CharField(blank=True, max_length=50)),
                ('estensione', models.CharField(blank=True, max_length=10)),
                ('percorso', models.CharField(max_length=500)),
                ('voto', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
