# Generated by Django 5.2.8 on 2025-11-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='locandina_url',
            field=models.URLField(blank=True, help_text="URL dell'immagine della locandina (opzionale)", max_length=500),
        ),
    ]
