# Generated by Django 5.2.8 on 2025-11-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_movie_locandina_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trama',
            field=models.TextField(blank=True, verbose_name='Trama'),
        ),
    ]
