# Generated by Django 5.2.8 on 2025-12-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_movie_trama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='anno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anno'),
        ),
    ]
