# Generated by Django 5.2.8 on 2025-12-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_movie_anno'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recensione',
            field=models.TextField(blank=True, null=True, verbose_name='Recensione'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ultima_visione',
            field=models.DateField(blank=True, null=True, verbose_name='Data ultima visione'),
        ),
    ]
