# Generated by Django 5.2.8 on 2025-12-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_movie_recensione_movie_ultima_visione'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='public_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Voto pubblico TMDB'),
        ),
        migrations.AddField(
            model_name='movie',
            name='public_votes',
            field=models.IntegerField(blank=True, null=True, verbose_name='N. voti TMDB'),
        ),
    ]
