# Generated by Django 5.2.8 on 2025-12-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_movie_public_rating_movie_public_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='critic_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Voto critica'),
        ),
        migrations.AddField(
            model_name='movie',
            name='critic_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='critic_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
