# Generated by Django 5.2.8 on 2025-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_movie_critic_rating_movie_critic_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='stato',
            field=models.CharField(blank=True, choices=[('todo', 'Da scaricare'), ('downloading', 'In download'), ('usb', 'On the USB'), ('done', 'Completed')], default='done', max_length=20),
        ),
    ]
