# Generated by Django 5.0.6 on 2025-11-25 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="films",
                to="films.director",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
